# Pre-Commit
# ==========
#
# Pre-Commit (https://pre-commit.com/) is a framework for handling the hooks
# for git to easily standardizez on linters, code-cleaners, security
# scanners, etc.
#
# Currently for Java repositories, we support the following hooks:
#
# - Detect Secrets (https://nasa-ammos.github.io/slim/docs/guides/software-lifecycle/security/secrets-detection/)
#
# Future hooks could include: trailing whitespace alerts, executable shebangs,
# debug statements left in code, Google code style adherence, etc.


---

repos:

-   repo: local
    hooks:
    - id: detect-secrets
      name: detect-secrets
      entry: scripts/detect_secrets_baseline.sh
      language: script
      pass_filenames: false

...

# -*- mode: YAML; tab-width: 4 -*-
