name: Secret Detection Workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    secret-detection:
        runs-on: ubuntu-latest
        if: github.actor != 'pdsen-ci'
        steps:
            -
                name: Checkout code
                uses: actions/checkout@v7
            -
                name: Install necessary packages
                run: |
                    pip install detect-secrets~=1.5.0

            -
                name: Create an initial .secrets.baseline if .secrets.baseline does not exist
                run: |
                    if [ ! -f .secrets.baseline ]; then
                        # This generated baseline file will only be temporarily available on the GitHub side and will not appear in the user's local files.
                        # Scanning an empty folder to generate an initial .secrets.baseline without secrets in the results.
                        echo "⚠️ No existing .secrets.baseline file detected. Creating a new blank baseline file."
                        mkdir empty-dir
                        detect-secrets scan empty-dir > .secrets.baseline
                        echo "✅ Blank .secrets.baseline file created successfully."
                        rm -r empty-dir
                    else
                        echo "✅ Existing .secrets.baseline file detected. No new baseline file will be created."
                    fi

            -
                name: Scan repository for secrets
                run: scripts/detect_secrets_baseline.sh
